#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-felix
Version  : 1.0.0
Release  : 1
URL      : https://repo1.maven.org/maven2/org/apache/felix/org.osgi.core/1.0.0/org.osgi.core-1.0.0.jar
Source0  : https://repo1.maven.org/maven2/org/apache/felix/org.osgi.core/1.0.0/org.osgi.core-1.0.0.jar
Source1  : https://repo1.maven.org/maven2/org/apache/felix/felix-parent/1.2.1/felix-parent-1.2.1.pom
Source2  : https://repo1.maven.org/maven2/org/apache/felix/felix-parent/2.1/felix-parent-2.1.pom
Source3  : https://repo1.maven.org/maven2/org/apache/felix/felix-parent/3/felix-parent-3.pom
Source4  : https://repo1.maven.org/maven2/org/apache/felix/felix/1.0.0/felix-1.0.0.pom
Source5  : https://repo1.maven.org/maven2/org/apache/felix/felix/1.0.2/felix-1.0.2.pom
Source6  : https://repo1.maven.org/maven2/org/apache/felix/maven-bundle-plugin/2.3.4/maven-bundle-plugin-2.3.4.jar
Source7  : https://repo1.maven.org/maven2/org/apache/felix/maven-bundle-plugin/2.3.4/maven-bundle-plugin-2.3.4.pom
Source8  : https://repo1.maven.org/maven2/org/apache/felix/maven-bundle-plugin/2.4.0/maven-bundle-plugin-2.4.0.jar
Source9  : https://repo1.maven.org/maven2/org/apache/felix/maven-bundle-plugin/2.4.0/maven-bundle-plugin-2.4.0.pom
Source10  : https://repo1.maven.org/maven2/org/apache/felix/maven-bundle-plugin/2.5.0/maven-bundle-plugin-2.5.0.jar
Source11  : https://repo1.maven.org/maven2/org/apache/felix/maven-bundle-plugin/2.5.0/maven-bundle-plugin-2.5.0.pom
Source12  : https://repo1.maven.org/maven2/org/apache/felix/maven-bundle-plugin/3.0.1/maven-bundle-plugin-3.0.1.jar
Source13  : https://repo1.maven.org/maven2/org/apache/felix/maven-bundle-plugin/3.0.1/maven-bundle-plugin-3.0.1.pom
Source14  : https://repo1.maven.org/maven2/org/apache/felix/org.apache.felix.bundlerepository/1.6.2/org.apache.felix.bundlerepository-1.6.2.jar
Source15  : https://repo1.maven.org/maven2/org/apache/felix/org.apache.felix.bundlerepository/1.6.2/org.apache.felix.bundlerepository-1.6.2.pom
Source16  : https://repo1.maven.org/maven2/org/apache/felix/org.apache.felix.bundlerepository/1.6.6/org.apache.felix.bundlerepository-1.6.6.jar
Source17  : https://repo1.maven.org/maven2/org/apache/felix/org.apache.felix.bundlerepository/1.6.6/org.apache.felix.bundlerepository-1.6.6.pom
Source18  : https://repo1.maven.org/maven2/org/apache/felix/org.apache.felix.utils/1.6.0/org.apache.felix.utils-1.6.0.jar
Source19  : https://repo1.maven.org/maven2/org/apache/felix/org.apache.felix.utils/1.6.0/org.apache.felix.utils-1.6.0.pom
Source20  : https://repo1.maven.org/maven2/org/apache/felix/org.osgi.core/1.0.0/org.osgi.core-1.0.0.jar
Source21  : https://repo1.maven.org/maven2/org/apache/felix/org.osgi.core/1.0.0/org.osgi.core-1.0.0.pom
Source22  : https://repo1.maven.org/maven2/org/apache/felix/org.osgi.service.obr/1.0.1/org.osgi.service.obr-1.0.1.jar
Source23  : https://repo1.maven.org/maven2/org/apache/felix/org.osgi.service.obr/1.0.1/org.osgi.service.obr-1.0.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-felix-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-felix package.
Group: Data

%description data
data components for the mvn-felix package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.osgi.core/1.0.0
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.osgi.core/1.0.0/org.osgi.core-1.0.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/felix-parent/1.2.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/felix-parent/1.2.1/felix-parent-1.2.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/felix-parent/2.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/felix-parent/2.1/felix-parent-2.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/felix-parent/3
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/felix-parent/3/felix-parent-3.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/felix/1.0.0
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/felix/1.0.0/felix-1.0.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/felix/1.0.2
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/felix/1.0.2/felix-1.0.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/maven-bundle-plugin/2.3.4
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/maven-bundle-plugin/2.3.4/maven-bundle-plugin-2.3.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/maven-bundle-plugin/2.3.4
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/maven-bundle-plugin/2.3.4/maven-bundle-plugin-2.3.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/maven-bundle-plugin/2.4.0
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/maven-bundle-plugin/2.4.0/maven-bundle-plugin-2.4.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/maven-bundle-plugin/2.4.0
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/maven-bundle-plugin/2.4.0/maven-bundle-plugin-2.4.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/maven-bundle-plugin/2.5.0
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/maven-bundle-plugin/2.5.0/maven-bundle-plugin-2.5.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/maven-bundle-plugin/2.5.0
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/maven-bundle-plugin/2.5.0/maven-bundle-plugin-2.5.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/maven-bundle-plugin/3.0.1
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/maven-bundle-plugin/3.0.1/maven-bundle-plugin-3.0.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/maven-bundle-plugin/3.0.1
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/maven-bundle-plugin/3.0.1/maven-bundle-plugin-3.0.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.bundlerepository/1.6.2
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.bundlerepository/1.6.2/org.apache.felix.bundlerepository-1.6.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.bundlerepository/1.6.2
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.bundlerepository/1.6.2/org.apache.felix.bundlerepository-1.6.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.bundlerepository/1.6.6
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.bundlerepository/1.6.6/org.apache.felix.bundlerepository-1.6.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.bundlerepository/1.6.6
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.bundlerepository/1.6.6/org.apache.felix.bundlerepository-1.6.6.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.utils/1.6.0
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.utils/1.6.0/org.apache.felix.utils-1.6.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.utils/1.6.0
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.utils/1.6.0/org.apache.felix.utils-1.6.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.osgi.core/1.0.0
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.osgi.core/1.0.0/org.osgi.core-1.0.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.osgi.core/1.0.0
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.osgi.core/1.0.0/org.osgi.core-1.0.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.osgi.service.obr/1.0.1
cp %{SOURCE22} %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.osgi.service.obr/1.0.1/org.osgi.service.obr-1.0.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.osgi.service.obr/1.0.1
cp %{SOURCE23} %{buildroot}/usr/share/java/.m2/repository/org/apache/felix/org.osgi.service.obr/1.0.1/org.osgi.service.obr-1.0.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/felix/felix-parent/1.2.1/felix-parent-1.2.1.pom
/usr/share/java/.m2/repository/org/apache/felix/felix-parent/2.1/felix-parent-2.1.pom
/usr/share/java/.m2/repository/org/apache/felix/felix-parent/3/felix-parent-3.pom
/usr/share/java/.m2/repository/org/apache/felix/felix/1.0.0/felix-1.0.0.pom
/usr/share/java/.m2/repository/org/apache/felix/felix/1.0.2/felix-1.0.2.pom
/usr/share/java/.m2/repository/org/apache/felix/maven-bundle-plugin/2.3.4/maven-bundle-plugin-2.3.4.jar
/usr/share/java/.m2/repository/org/apache/felix/maven-bundle-plugin/2.3.4/maven-bundle-plugin-2.3.4.pom
/usr/share/java/.m2/repository/org/apache/felix/maven-bundle-plugin/2.4.0/maven-bundle-plugin-2.4.0.jar
/usr/share/java/.m2/repository/org/apache/felix/maven-bundle-plugin/2.4.0/maven-bundle-plugin-2.4.0.pom
/usr/share/java/.m2/repository/org/apache/felix/maven-bundle-plugin/2.5.0/maven-bundle-plugin-2.5.0.jar
/usr/share/java/.m2/repository/org/apache/felix/maven-bundle-plugin/2.5.0/maven-bundle-plugin-2.5.0.pom
/usr/share/java/.m2/repository/org/apache/felix/maven-bundle-plugin/3.0.1/maven-bundle-plugin-3.0.1.jar
/usr/share/java/.m2/repository/org/apache/felix/maven-bundle-plugin/3.0.1/maven-bundle-plugin-3.0.1.pom
/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.bundlerepository/1.6.2/org.apache.felix.bundlerepository-1.6.2.jar
/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.bundlerepository/1.6.2/org.apache.felix.bundlerepository-1.6.2.pom
/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.bundlerepository/1.6.6/org.apache.felix.bundlerepository-1.6.6.jar
/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.bundlerepository/1.6.6/org.apache.felix.bundlerepository-1.6.6.pom
/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.utils/1.6.0/org.apache.felix.utils-1.6.0.jar
/usr/share/java/.m2/repository/org/apache/felix/org.apache.felix.utils/1.6.0/org.apache.felix.utils-1.6.0.pom
/usr/share/java/.m2/repository/org/apache/felix/org.osgi.core/1.0.0/org.osgi.core-1.0.0.jar
/usr/share/java/.m2/repository/org/apache/felix/org.osgi.core/1.0.0/org.osgi.core-1.0.0.pom
/usr/share/java/.m2/repository/org/apache/felix/org.osgi.service.obr/1.0.1/org.osgi.service.obr-1.0.1.jar
/usr/share/java/.m2/repository/org/apache/felix/org.osgi.service.obr/1.0.1/org.osgi.service.obr-1.0.1.pom
